---

- hosts: all
  become: true
  tasks:
  
  - name: update repository index for Ubuntu
     apt:
       update_cache: yes
     when: ansible_distribution == "Ubuntu"

  - name: add php support for apache
    apt:
      name: 
        -libapache2-mod-php
        -apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  
